### ISSUE TITLE
Nightly Builds Fail [API-1527]

### ISSUE THREAD

**Issue by hakanaktas0** [hazelcast/hazelcast-cpp-client#1012]
Release builds of all nightly builds fail as seen [here](https://github.com/hazelcast/hazelcast-cpp-client/actions).

**Comment by hakanaktas0** [comment]
Only release builds fail for Ubuntu and MacOS. 
All builds fail for Windows. For Windows problem seems to be related to boost install.
Logs:
[Ubuntu Logs.zip](https://github.com/hazelcast/hazelcast-cpp-client/files/9433965/Ubuntu.Logs.zip)
[MacOS Logs.zip](https://github.com/hazelcast/hazelcast-cpp-client/files/9433966/MacOS.Logs.zip)
[Windows Logs.zip](https://github.com/hazelcast/hazelcast-cpp-client/files/9433967/Windows.Logs.zip)
"

**Comment by hakanaktas0** [comment]
Changing windows version to 2019 fixes boost installation error.

**Comment by OzanCansel** [comment]
- Ubuntu builds fail because of undefined reference error and fix #1022 also solves this issue.
- MacOS release builds fail because we treat a warning as an error and new version of boost which generates a warning message which tells that language standard of Boost.Math module will be increased to C++14 in July 2023.
- Windows builds fail because windows-latest update to windows-2022 and it comes with VS17-2022 toolchain which boost is compilable only after 1.78 version but the action downloads 1.76.0.
