### ISSUE TITLE
C++ Event Listener register a callback function

### ISSUE THREAD

**Issue by KalebNeguisse** [hazelcast/hazelcast-cpp-client#358]
Hi,

I see currently, that I can register a listener to a map, and when a given event happens a specific event handler can be triggers. My question is can we instead register a function. In other words can I register a listener so when event A happens, I would like a function A_EVENT be called. The way I see the example here http://docs.hazelcast.org/docs/clients/cpp/3.6/ is a class called SampleEntryListener which has methods that are invoked. I want to register a function otuside the listner class, that will be called. It is possible.

Thank you for your time and I await your response

Kaleb

**Comment by ihsandemir** [comment]
Hello @KalebNeguisse 

Thanks for the question. Our listener registration api works with certain interface implementations such as EntryListener. If you want a certain function be called upon an entry received, can you do something like this:

            class FunctionBasedListener : public EntryAdapter<int, int> {
            public:
                virtual void entryAdded(const EntryEvent<int, int> &event) {
                    A_EVENT(event);
                }
            };

Is this what you want to do?

Note: Please use google groups for such questions since it is useful for other people as well.

Regards,
ihsan
