### ISSUE TITLE
IMap.values()  lost references.

### ISSUE THREAD

**Issue by arbox0** [hazelcast/hazelcast-cpp-client#467]
Hello!

I am using Hazelcast client in a project and I have found what seems to be an issue.
I have one class that contains an attribute which is a pointer to another class.
I create that pointer in the constructor and destroy the pointer in destructor...

When I access this class using map.get. It works properly...
When I access this class using map.values() it crashes...

The cause seems to be in values() implementation in ClientMapProxy : 
`std::vector<V> values() {`
      `std::vector<serialization::pimpl::Data> dataResult = proxy::IMapImpl::valuesData();`
       `size_t size = dataResult.size();`
        `std::vector<V> values(size);`
        `for (size_t i = 0; i < size; ++i) {`
               `std::auto_ptr<V> value = toObject<V>(dataResult[i]);`
               `values[i] = *value;`
          `}`
           `return values;`
`}`

each iteration creates a local variable "value" which is "disposed" at the beginning of the next iteration, that causes a call which destroys the content of that auto_ptr value making a call to my class destructor. I think that instead of " values[i] = *value;" , this function should return a vector of auto_ptr<V>... "values[i] = value;".

I have attached an example of my issue. Just change example.txt to example.cpp.

Regards!

[Example.txt](https://github.com/hazelcast/hazelcast-cpp-client/files/2561991/Example.txt)

**Comment by ihsandemir** [comment]
Hello @arbox0 
The assignment `values[i] = *value;` requires that you implement a proper `copy assignment/constructor` for your object.  When I examine the Person class, the private attribute `name` is a pointer. Since you do not have any copy constructor implemented, the compiler generated copy constructor will copy the pointer address only. Since, the copied from object is destroyed, the newly created object's `name` pointer points to an invalid memory location which would cause the problem. Hence, the solution is to implement a proper copy constructor. e.g:
```
    Person(const Person &rhs) {
        this->operator=(rhs);
    }

    Person& operator=(const Person &rhs) {
        if (!rhs.name) {
            this->name = NULL;
        } else {
            this->name = new PersonName(*rhs.name);
        }
        return *this;
    }
```
The reason why we return stack allocated vector of objects `std::vector<V>` is for user convernience in most cases and also due to historical reasons. But if you do not want to copy objects and just work with pointers then I recommend that you use `RawPointerMap` which is the same map but interface is adopted to use raw pointers instead. Hence, you can get an array of your object pointers using the `RawPointerMap` as: `std::auto_ptr<DataArray<V> > values()`. Further on RawPointerMap usages are here: [Raw Pointer API] (https://github.com/hazelcast/hazelcast-cpp-client/tree/v3.10.1#raw-pointer-api)   and [Example code] (https://github.com/hazelcast/hazelcast-cpp-client/blob/v3.10.1/examples/adaptor/RawMap.cpp)This api does not do copy hence you will not need copy constructor.

Let me know if this helps you solve the problem.

**Comment by arbox0** [comment]
Hi @ihsandemir!!

Thank you very much for your answer!!!
The copy constructor worked like a charm!!

Thanks again!
