### ISSUE TITLE
Unresolved getMap getQueue

### ISSUE THREAD

**Issue by yigitmultibankfx** [hazelcast/hazelcast-cpp-client#563]
Using "Visual Studio 2019"
When I try to use getMap or getQueue I get linking error although I show the correct .lib version. Do I have to reference the dll file too? HazelCastClient object referencing works well I get linking error only when I call getMap getQueue etc.

Here is the linking error I receive:

LNK2019	unresolved external symbol "__declspec(dllimport) public: __thiscall hazelcast::client::serialization::pimpl::Data::Data(class hazelcast::client::serialization::pimpl::Data &&)" (__imp_??0Data@pimpl@serialization@client@hazelcast@@QAE@$$QAV01234@@Z) referenced in function "public: static void __cdecl std::_Default_allocator_traits<class std::allocator<class hazelcast::client::serialization::pimpl::Data> >::construct<class hazelcast::client::serialization::pimpl::Data,class hazelcast::client::serialization::pimpl::Data>(class std::allocator<class hazelcast::client::serialization::pimpl::Data> &,class hazelcast::client::serialization::pimpl::Data * const,class hazelcast::client::serialization::pimpl::Data &&)" (??$construct@VData@pimpl@serialization@client@hazelcast@@V12345@@?$_Default_allocator_traits@V?$allocator@VData@pimpl@serialization@client@hazelcast@@@std@@@std@@SAXAAV?$allocator@VData@pimpl@serialization@client@hazelcast@@@1@QAVData@pimpl@serialization@client@hazelcast@@$$QAV34567@@Z)	ManagerToDistributedMap	D:\Projects\C++\ManagerToDistributedMap\ManagerToDistributedMap\ManagerToDistributedMap\ManagerToDistributedMap.obj	1

**Comment by ihsandemir** [comment]
Hello @yigitmultibankfx There may be a few thing to double check:

1. Are you using 64-bit or 32-bit application and did you point to the correct type library?
2. Did you use the compile flag as describe here?: https://github.com/hazelcast/hazelcast-cpp-client#1313-windows-client

I suspect it is mostly due to item 2.


1.

**Comment by yigitmultibankfx** [comment]
Hi,

1- I am using the 32-bit application

2- I defined the compile flag as HAZELCAST_USE_SHARED. If I do not define that flag there are much more linking errors so I know that I actually set that. 

Here is how I can simply generate the error:

1- I create a simple console app with Visual Studio 2019. The active configuration is default as "Debug x86"

2- I add the following two paths to the "VC++ Include Directories":
cpp\Windows_32\external\include
cpp\Windows_32\hazelcast\include
(these are coming from the extracted folders of https://download.hazelcast.com/clients/3.12/hazelcast-cpp-client-3.12-Windows_32.zip)

3- I add HAZELCAST_USE_SHARED to the C++/Preprocessor/Preprocessor Definitions

4- I add the following line to Linker/Additional Library Directories:
"cpp\Windows_32\hazelcast\lib\shared\HazelcastClient3.12_32.lib"

5- I add the following include line to my "main" method:
#include <hazelcast/client/HazelcastClient.h>

6- I add the following lines to my "main" method:
hazelcast::client::HazelcastClient hz;
hazelcast::client::IMap<int, int> map = hz.getMap<int, int>("somemap");

And I get the following error:
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __thiscall hazelcast::client::serialization::pimpl::Data::Data(class hazelcast::client::serialization::pimpl::Data &&)" (__imp_??0Data@pimpl@serialization@client@hazelcast@@QAE@$$QAV01234@@Z) referenced in function "public: static void __cdecl std::_Default_allocator_traits<class std::allocator<class hazelcast::client::serialization::pimpl::Data> >::construct<class hazelcast::client::serialization::pimpl::Data,class hazelcast::client::serialization::pimpl::Data>(class std::allocator<class hazelcast::client::serialization::pimpl::Data> &,class hazelcast::client::serialization::pimpl::Data * const,class hazelcast::client::serialization::pimpl::Data &&)" (??$construct@VData@pimpl@serialization@client@hazelcast@@V12345@@?$_Default_allocator_traits@V?$allocator@VData@pimpl@serialization@client@hazelcast@@@std@@@std@@SAXAAV?$allocator@VData@pimpl@serialization@client@hazelcast@@@1@QAVData@pimpl@serialization@client@hazelcast@@$$QAV34567@@Z)	ConsoleApplication1

If I do not add the second line which gets the map, there are no errors at all so I know I do not fail to link the hazelcast library as a whole. There has to be some other thing that I am missing.

Kind Regards

**Comment by ihsandemir** [comment]
Did you try "Release x86" configuration as well?

**Comment by ihsandemir** [comment]
@yigitmultibankfx  I will try your suggestion in windows machine and see if I can generate the problem.

**Comment by yigitmultibankfx** [comment]
I tried with the exact same configuration properties for "Release x86"
and got a shorter version of the same error I believe:

Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: __thiscall hazelcast::client::serialization::pimpl::Data::Data(class hazelcast::client::serialization::pimpl::Data &&)" (__imp_??0Data@pimpl@serialization@client@hazelcast@@QAE@$$QAV01234@@Z)	ConsoleApplication1

**Comment by yigitmultibankfx** [comment]
Anything on this one yet? Actually if this is not doable with visual studio, it will decide whether or not I am able to use Hazelcast in my project.

Thank you

**Comment by ihsandemir** [comment]
> Anything on this one yet? Actually if this is not doable with visual studio, it will decide whether or not I am able to use Hazelcast in my project.
> 
> Thank you

I could not find time to try it yesterday. I will try it today. I will update on the issue.

**Comment by yigitmultibankfx** [comment]
thank you ! really really appreciated. very eager to move forward with it.

**Comment by ihsandemir** [comment]
Hello @yigitmultibankfx I think this may be your problem:

Step 4: `4- I add the following line to Linker/Additional Library Directories:
"cpp\Windows_32\hazelcast\lib\shared\HazelcastClient3.12_32.lib"` This is wrong. Add the folder only here and add `HazelcastClient3.12_32.lib` to the Linker->Inputs->Additional Dependencies.

I tried with the fix and it works (my VS version is lower but I assume it should not matter for this case), I am attaching the screenshots of the problematic configuration. Let me know if this solves your problem.

<img width="1270" alt="Screen Shot 2019-09-10 at 15 19 24" src="https://user-images.githubusercontent.com/7543261/64613518-05346b80-d3df-11e9-976b-661c7ded2b7a.png">
<img width="1267" alt="Screen Shot 2019-09-10 at 15 19 38" src="https://user-images.githubusercontent.com/7543261/64613519-05cd0200-d3df-11e9-9272-4f15f2abe1ec.png">

**Comment by yigitmultibankfx** [comment]
Still same linking error. Did not solve anything. I will try to find and install VS 2015 to try. But your latest version seem to need some extra touch in the VS 2019 project settings part, to work.

**Comment by yigitmultibankfx** [comment]
Moreover, if it is a setting error at my side, why does it generate a linking error only for a specific class? If I remove the linking setup lines totally, it properly and expectedly generates lots of linking errors. But how can I do something wrong to cause a linking error only in that serialization.pimpl.Data class? it does not make sense to me to be honest.

**Comment by ihsandemir** [comment]
Ok, lets research further. I will try install VS 2019 and try to generate the problem.

**Comment by yigitmultibankfx** [comment]
Would it help if I upload my simple project to somewhere and provide a link for you?

**Comment by ihsandemir** [comment]
yes, you can upload and share.

**Comment by yigitmultibankfx** [comment]
Here it is:
https://www.dropbox.com/s/lj50vogevyv5pqi/TryHZ.rar?dl=0

All you need to do is change the links in these setttings:
VC++/Include Directories
Linker/All Options/Additional Library Directories

Thanks..

**Comment by ihsandemir** [comment]
I downloaded and opened your project in VS community 2013 and was able to compile with no problems after correcting the paths. 

I also downloaded VS 2019, when I tried the above solution, I got a similar error as you get and also a weird error:
`Unknown compiler version - please run the configure tests and report the results`

The VS 2019 Platform Toolset is v142 and that seems to cause this error since when I choose older Platform Toolset v120, it works. We need to figure out what is the cause here.

By the way, you can always build a new library with your Platform Toolset in the worst case from source code if we can not solve the problem. It is cmake based build for the project source code.

**Comment by ihsandemir** [comment]
@yigitmultibankfx I just looked more into the issue and it may be a problem of c++ standar language level being C++14 by default. I see that the error is related to the expected move constructor of the `Data` class which is only after C++11 standard. 
The error:
`"__declspec(dllimport) public: __thiscall hazelcast::client::serialization::pimpl::Data::Data(class hazelcast::client::serialization::pimpl::Data **&&**)"`

We built our library backward compatible with C++98 so that old compiler users can also use the library as well. I could not find a way to set a lower language level for the project in VS 2019 but I have a feeling this may be related to the problem. (yet to confirm)

**Comment by yigitmultibankfx** [comment]
There are more problems when you use something over c++12. I will give feedback to you on this, whenever I have time. It was simply when you run a vector trace on a map. When the map has, let's say, more than 10 elements in it, the simple sample that is in the main github page, crashes. And with doing nothing other than just a the tool set downgrade to v120, it works perfectly.

**Comment by ihsandemir** [comment]
@yigitmultibankfx This issue should be solved now with 4.0 release and we will be doing source only releases starting with 4.0 so that you will easily be able to generate the library in your own environment, hence no such compiler version issues. Please try the new 4.0-BETA and let me know if you see any problems generating the library or using it.
