### ISSUE TITLE
Connection log timestamp contains negative msecs

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast-cpp-client#892]
@ihsandemir  Hi - I'll test that tomorrow. Also - in the last read / last write time area - I got an odd log from the library with a negative millisecond timestamp - see "lastReadTime=2021-06-23 15:35:58.-67" in the log below.

```
2021/06/23-15:35:58.768856 +0000: (90): INFO: Discovery: Library - <hz.client_1><soaktest> ClientConnection{alive=0, connectionId=5, remoteEndpoint=Address[10.42.4.229:5701], lastReadTime=2021-06-23 15:35:58.-67, closedTime=2021-06-23 15:35:58.000, connected server version=4.0.3} closed. Reason: Socket read error. asio.misc:2 for ClientConnection{alive=1, connectionId=5, remoteEndpoint=Address[10.42.4.229:5701], lastReadTime=2021-06-23 15:35:58.-67, closedTime=never, connected server version=4.0.3}
.0.3}
```

_Originally posted by @andysCaplin in https://github.com/hazelcast/hazelcast-cpp-client/issues/883#issuecomment-866994276_

This seems to happen if the timestamp is before the current time in the system.

**Comment by andysCaplin** [comment]
@ihsandemir I rebuilt my application with the new library and I'm not getting the disconnects any more.

Could I ask you a question about client-server interaction ?

We have a setup where we have multiple servers ( Java 4.0 ) and one client. ( C++ 4.0 ) Say Server1, Server2, Server3 and Client1
Everything is started and connected.

If we break the network connection between Server1 and Client1 we get what looks like inconsistent behaviour
- Client1 sees a socket error but does not get a CLIENT_DISCONNECTED lifecycle event - which seems correct because we have other servers available
- Server1 gets a CLIENT_DISCONNECTED lifecycle event for the Client1
- If we stop Server2 and Server3 then Client1 will get a CLIENT_DISCONNECTED lifecycle event.

Is that correct ? 
And if so, how do we distinguish at the server level the difference between a client disconnecting from a server and if we stop it completely ? 
Do we need to have some reference counting scheme at the server ?
